version: '3.1'
services:
  database:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: productdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes: [
      '$HOME/data/postgres/productdb:/var/lib/postgresql/data'
      ]
  elasticsearch:
    container_name: product_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic
networks:
  elastic:
    driver: bridge 
